baseURL = "https://blog.pepamraz.cz/"
defaultContentLanguage = "cs"
languageCode = "cs"
title = 'Sarkastick칳 blog o programov치n칤 - blog.pepamraz.cz 游눹'
theme = 'PaperMod'
relativeURLs = true
canonifyURLs = true

[params]
[params.homeInfoParams]
  Title = "Sarkastick칳 blog o programov치n칤 游눹"
  Content = """
  V칤tejte na m칠m blogu, kde se sarkasmus a programov치n칤 setk치vaj칤! 
  Tento blog je v캩nov치n v코em, kte콏칤 se cht캩j칤 dozv캩d캩t v칤ce o programov치n칤, 
  ale z치rove켿 se cht캩j칤 pobavit. Najdete zde 캜l치nky pln칠 u쬴te캜n칳ch informac칤, 
  tip콢 a trik콢, ale tak칠 vtipn칳ch pozn치mek a sarkastick칳ch koment치콏콢. 
  P콏ipojte se k n치m a u쬴jte si cestu sv캩tem k칩du s 칰sm캩vem na tv치콏i!
  """


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/pepamraz"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@pepa_mraz"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/pepamraz/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  social = "social"
